### ISSUE TITLE
Interface description of UPI

### ISSUE THREAD

**Issue by dkdndes** [fostinno/AwesomeUPI#1]

**Comment by dkdndes** [comment]
I checked stackoverflow.com but I could not find any references, and does an Open Source Repository with the interface description exist already? I like to check it again W3C Payments, etc.

**Comment by dkdndes** [comment]
Found it: 

* https://digidhan.mygov.in/pages/pdf/sbi/NPCI%20Unified%20Payment%20Interface.pdf

**Comment by dkdndes** [comment]
Additional:

* https://cashlessconsumer.github.io/CashlessConsumer/upi-setup.html

Maybe worth to add them here?

**Comment by maheshkumaryadav** [comment]
Thanks. Valueable links. Added both.
